- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/ServerInfo/_Mini/Service/Service.xml"
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chef
  - Janitorial

- type: guideEntry
  id: Bartender
  name: guide-entry-bartender
  text: "/ServerInfo/_Mini/Service/Bartender.xml"
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: guide-entry-botany
  text: "/ServerInfo/_Mini/Service/Botany.xml"

- type: guideEntry
  id: Chef
  name: guide-entry-chef
  text: "/ServerInfo/_Mini/Service/Chef.xml"

- type: guideEntry
  id: Janitorial
  name: guide-entry-janitorial
  text: "/ServerInfo/_Mini/Service/Janitorial.xml"
